trigger:
- master

jobs:
  - job: linux
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - template: ./build-unix.yml
        parameters:
          name: linux
  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - template: ./build-unix.yml
        parameters:
          name: macOS
  - job: release
    dependsOn: [ "linux", "macOS" ]
    variables:
      linuxReleased: $[ dependencies.linux.outputs['maybeRelease.isRelease'] ]
      macOSReleased: $[ dependencies.macOS.outputs['maybeRelease.isRelease'] ]
    condition: and(succeeded(),
                   eq( variables['linuxReleased'], 'true'),
                   eq( variables['macOSReleased'], 'true'))
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - checkout: self
        persistCredentials: true
      - bash: |
          set -euxo pipefail
          git tag v$(release_tag)
          git push origin v$(release_tag)
      - task: GitHubRelease@0
        inputs:
          gitHubConnection: 'garyverhaegen-da'
          repositoryName: '$(Build.Repository.Name)'
          action: 'create'
          target: '$(Build.SourceVersion)'
          tagSource: 'auto'
          assets: '$(Build.ArtifactStagingDirectory)'
          assetUploadMode: 'replace'
          addChangeLog: false
          isDraft: true
