trigger:
- master

jobs:
  - job: linux
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - template: ./build-unix.yml
      parameters:
        name: linux
  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - template: ./build-unix.yml
      parameters:
        name: macOS
  - job: vars
    dependsOn: [ "linux", "macOS" ]
    variables:
      linuxReleased: $[ dependencies.linux.outputs['maybeRelease.has_released'] ]
      macOSReleased: $[ dependencies.macOS.outputs['maybeRelease.has_released'] ]
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - checkout: self
      persistCredentials: true
    - bash: |
        echo ---1
        echo $(linuxReleased)
        echo ---2
        echo $(macOSReleased)
  - job: release
    dependsOn: [ "linux", "macOS" ]
    variables:
      linuxReleased: $[ dependencies.linux.outputs['maybeRelease.has_released'] ]
      macOSReleased: $[ dependencies.macOS.outputs['maybeRelease.has_released'] ]
    condition: and(succeeded(),
                   eq( variables['linuxReleased'], 'true'),
                   eq( variables['macOSReleased'], 'true'))
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - checkout: self
      persistCredentials: true
    - bash: |
        set -euxo pipefail
        git tag v$(release_tag)
        git push origin v$(release_tag)
    - task: GitHubRelease@0
      inputs:
        gitHubConnection: 'garyverhaegen-da'
        repositoryName: '$(Build.Repository.Name)'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'auto'
        assets: '$(Build.ArtifactStagingDirectory)'
        assetUploadMode: 'replace'
        addChangeLog: false
        isPrerelease: true
