trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- bash: ./build.sh
  displayName: 'build'
- bash: ./release.sh
  displayName: 'maybe release'
- bash: |
    set -euxo pipefail
    echo before
    git -c user.name=Azure -c user.email=info@digitalasset.com tag v$(release_tag)
    echo between
    git -c user.name=Azure -c user.email=info@digitalasset.com push origin v$(release_tag)
    echo befter
  condition: eq(variables['has_released'], 'true')
- task: GitHubRelease@0
  condition: eq(variables['has_released'], 'true')
  inputs:
    gitHubConnection: 'garyverhaegen-da'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    #title: # Optional
    #releaseNotesSource: 'file' # Optional. Options: file, input
    #releaseNotesFile: # Optional
    #releaseNotes: # Optional
    assets: '$(Build.ArtifactStagingDirectory)/out/hello'
    assetUploadMode: 'replace'
    addChangeLog: false
