trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
- bash: ./build.sh
  displayName: 'build'
- bash: ./release.sh
  displayName: 'maybe release'
- bash: |
    set -euxo pipefail
    echo before
    git tag v$(release_tag)
    echo between
    git push origin v$(release_tag)
    echo befter
    find .
    pwd
    echo $(Build.ArtifactStagingDirectory)
  condition: eq(variables['has_released'], 'true')
- task: GitHubRelease@0
  condition: eq(variables['has_released'], 'true')
  inputs:
    gitHubConnection: 'garyverhaegen-da'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    title: "Linux build"
    assets: './out/hello'
    assetUploadMode: 'replace'
    addChangeLog: false
